@startuml 会議室予約ドメインモデル
skinparam componentStyle rectangle

' ユーザ
[ユーザ] o-- [ユーザID]
[ユーザ] o-- [パスワード]
[ユーザ] o-- [名前]

' 会議室
[会議室] o-- [会議室名]
[会議室] o-- [座席数]
[会議室] o-- [設備情報]

' 予約
[予約] o-- [予約番号]
[予約] o-- [利用日時]
[予約] o-- [目的]

@enduml
